# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/86187/Desktop/pipeline交/pipeline.cache/wt [current_project]
set_property parent.project_path C:/Users/86187/Desktop/pipeline交/pipeline.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/86187/Desktop/pipeline交/pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/D_mem.coe
add_files c:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/I_mem.coe
read_verilog -library xil_defaultlib {
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/Counter_3_IO.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/EX.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/ctrl_encode_def.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/EXT.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/ID.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/IF.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/MEM.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/MIO_BUS_IO.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/Multi_8CH32_IO.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/NPC.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/PC.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/PipeCPU.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/RF.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SAnti_jitter_IO.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SEnter_2_32_IO.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SPIO_IO.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SSeg7_Dev_IO.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/alu.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/clk_div.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/ctrl.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/forward.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/hazard.v
  C:/Users/86187/Desktop/pipeline交/pipeline.srcs/top.v
}
read_ip -quiet C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/ip/RAM_B/RAM_B.xci
set_property used_in_implementation false [get_files -all c:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/ip/RAM_B/RAM_B_ooc.xdc]

read_ip -quiet C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all c:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

read_edif C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SEnter_2_32.ngc
read_edif C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SAnti_jitter.ngc
read_edif C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SPIO.ngc
read_edif C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SSeg7_Dev.ngc
read_edif C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/Multi_8CH32.ngc
read_edif C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/MIO_BUS.ngc
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/86187/Desktop/icf-v-p.xdc
set_property used_in_implementation false [get_files C:/Users/86187/Desktop/icf-v-p.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top IP2SOC_TOP -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef IP2SOC_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file IP2SOC_TOP_utilization_synth.rpt -pb IP2SOC_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
