# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/86187/Desktop/pipeline交/pipeline.runs/synth_1/.Xil/Vivado-19056-LAPTOP-L1154LH9/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/ip/RAM_B
    c:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/ip/ROM_D
  } D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    c:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/ip/RAM_B
    c:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/ip/ROM_D
  } {
      C:/Users/86187/Desktop/pipeline交/pipeline.runs/synth_1/.Xil/Vivado-19056-LAPTOP-L1154LH9/realtime/RAM_B_stub.v
      C:/Users/86187/Desktop/pipeline交/pipeline.runs/synth_1/.Xil/Vivado-19056-LAPTOP-L1154LH9/realtime/ROM_D_stub.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/Counter_3_IO.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/EX.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/ctrl_encode_def.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/EXT.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/ID.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/IF.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/MEM.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/MIO_BUS_IO.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/Multi_8CH32_IO.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/NPC.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/PC.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/PipeCPU.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/RF.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SAnti_jitter_IO.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SEnter_2_32_IO.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SPIO_IO.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/SSeg7_Dev_IO.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/alu.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/IO/clk_div.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/ctrl.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/forward.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/sources_1/Hzpipelinecpu/hazard.v
      C:/Users/86187/Desktop/pipeline交/pipeline.srcs/top.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top IP2SOC_TOP
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/86187/Desktop/pipeline交/pipeline.runs/synth_1/.Xil/Vivado-19056-LAPTOP-L1154LH9/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
